# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marke# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#87afff" }

# Hovered
hovered = { fg = "#262626", bg = "#87afff" }
preview_hovered = { underline = false }

# Find
find_keyword = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#afd75f", bg = "#afd75f" }
marker_copied = { fg = "#d7af5f", bg = "#d7af5f" }
marker_cut = { fg = "#ff8787", bg = "#ff8787" }
marker_marked = { fg = "lightcyan", bg = "lightcyan" }


# Count
count_copied = { fg = "white", bg = "green" }
count_cut = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

# Border
border_symbol = "│"
border_style = { fg = "#afd7ff" }

# Highlighting
syntect_theme = ""

# : }}}

# : Tabs {{{

[tabs]
active = { fg = "#262626", bg = "#87afff", bold = true }
inactive = { fg = "white", bg = "#4e4e4e" }
tab_width = 1

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#262626", bg = "#afd7ff", bold = true }
normal_alt  = { fg = "#7aa2f7", bg = "#292e42" }

# Select mode
select_main = { fg = "#262626", bg = "#afd75f", bold = true }
select_alt  = { fg = "#7aa2f7", bg = "#292e42" }

# Unset mode
unset_main = { fg = "#262626", bg = "#af87ff", bold = true }
unset_alt  = { fg = "#7aa2f7", bg = "#292e42" }

# : }}}

# : Status {{{

[status]
overall = { fg = "#4e4e4e", bg = "#4e4e4e" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error = { fg = "red", bg = "black" }

# Permissions
perm_type = { fg = "#afd75f" }
perm_read = { fg = "#d7af5f" }
perm_write = { fg = "#ff8787" }
perm_exec = { fg = "#87d7ff" }
perm_sep = { fg = "#4e4e4e" }

# : }}}


# : Select {{{

[pick]
border = { fg = "cyan" }
active = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "cyan" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "cyan" }
active = { bg = "darkgray" }
inactive = {}

# Icons
icon_file = ""
icon_folder = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "cyan" }
title = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#262626" }
# cand            = { fg = "#87d7ff" }
# rest            = { fg = "darkgray" }
# desc            = { fg = "#af87ff" }
cand = { fg = "lightcyan" }
rest = { fg = "darkgray" }
desc = { fg = "magenta" }
separator = "  "
separator_style = { fg = "darkgray", bold = true }

# : }}}


# : Help {{{

[help]
on = { fg = "#af87ff" }
run = { fg = "#87d7ff" }
desc = { fg = "#afafd7" }
hovered = { bg = "#4e4e4e", bold = true }
footer = { fg = "#262626", bg = "white" }

# : }}}

# : Notify {{{

[notify]
title_info = { fg = "green" }
title_warn = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

# : }}}
#
# : File-specific styles {{{
[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#e0af68" },

	# Media
	{ mime = "video/*", fg = "#f7768e" },
	{ mime = "audio/*", fg = "#f7768e" },

	# Archives
	{ mime = "application/zip",             fg = "#bb9af7" },
	{ mime = "application/x-tar",           fg = "#bb9af7" },
	{ mime = "application/x-bzip*",         fg = "#bb9af7" },
	{ mime = "application/x-bzip2",         fg = "#bb9af7" },
	{ mime = "application/x-7z-compressed", fg = "#bb9af7" },
	{ mime = "application/x-rar",           fg = "#bb9af7" },
	{ mime = "application/x-xz",            fg = "#bb9af7" },

	# Documents
	{ mime = "application/doc",        fg = "#9ece6a" },
	{ mime = "application/epub+zip",   fg = "#9ece6a" },
	{ mime = "application/pdf",        fg = "#9ece6a" },
	{ mime = "application/rtf",        fg = "#9ece6a" },
	{ mime = "application/vnd.*",      fg = "#9ece6a" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#7aa2f7" }
]

# : }}}
